version: '3.9'

services:
  pytorch-cs:
    container_name: pytorch-cs
    image: ghcr.io/works-on-my-machine/pytorch-code-server:1.6.0
    environment:
      - "DISPLAY=pytorch-novnc:0.0"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
    networks:
      - pytorch-network
    ports:
      - 8443:8443
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - "${CS_PROJECTS_VOLUME}:/projects"
  pytorch-novnc:
    container_name: pytorch-novnc
    image: "theasp/novnc:latest"
    environment:
      - "DISPLAY_WIDTH=${NOVNC_WIDTH}"
      - "DISPLAY_HEIGHT=${NOVNC_HEIGHT}"
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
    networks:
      - pytorch-network
    restart: unless-stopped
    ports:
      - 6060:8080

networks:
  pytorch-network: